### PR TITLE
Vb 12 filter the requests

### LINKED ISSUE #95: VB-12: filter the requests based on first, last name and phone/landline
GET /api/requests
Media type: Application/json

Description:
Method should filter returned records by query parameters.

Query parameters:
- page
    default: 0
- page_size
    default: 30
- first_name
- last_name
- phone
- zone
- created_at

Responses:
200: An array of request objects
Example value:
```
{
"metadata": {
"page": "0",
"page_size": "30",
"page_count":  "5",
"total_count": "100"
},
"records":
[
{
  "id": "1"
  "beneficiary": "beneficiary_id",
  "user": "user_id",
  "status": "new",
  "secret": "string",
  "urgent": false,
  "comments": "string",
  "has_symptoms": false,
  "cluster": "cluster_id",
  "created_at": "2020-09-10T21:31:16.741Z"
},
{
  "id": "2"
  "beneficiary": "beneficiary_id",
  "user": "user_id",
  "status": "new",
  "secret": "string",
  "urgent": false,
  "comments": "string",
  "has_symptoms": false,
  "cluster": "cluster_id",
  "created_at": "2020-09-10T21:31:16.741Z"
}
]
}
```
400: Bad request
Example value:
```
{
  "code": "string",
  "message": "string"
}
```
401: Unauthorized Access
Example value:
`Unauthorized Access`

### PR DESCRIPTION
**Pull request by serghei-rubailo**
### What does it fix?

Closes #95 

1. Have added get_requests_by_query_filters() method for requests to search by beneficiaries.
**Please note**, now it searches by exact match, if we need to search by not exact match, please reply.
I wasn't able to use the existing method for requests searching. If the existing method should be used, please reply, but it will take time to review it.
2. Change swagger for new method

If some adjustments should be made, please reply.

### How has it been tested?

1. http://localhost:5000/api/requests?pages=1&page_size=2&first_name=Jora
```
{
  "metadata": {
    "page": 1,
    "page_count": 3,
    "page_size": 2,
    "total_count": 5
  },
  "records": [
    {
      "_id": "5fafc2326dc14fbacea2cde1",
      "beneficiary": "5fafc2326dc14fbacea2cddf",
      "comments": "Right range heart general. Both ok sing simple good morning dream. Yard serious charge from all everybody.",
      "created_at": "Wed, 01 Jan 2020 00:00:00 GMT",
      "has_symptoms": false,
      "number": 3500,
      "status": "new",
      "type": "warm_lunch",
      "urgent": false,
      "user": "5fafc2316dc14fbacea2cdd4"
    },
    {
      "_id": "5fafc2326dc14fbacea2cde2",
      "beneficiary": "5fafc2326dc14fbacea2cddf",
      "cluster": "5fafc2326dc14fbacea2cde0",
      "comments": "Travel born yeah movement add new while speech. Woman item need. Appear doctor soldier you teacher her. Arm provide her man seek stuff near.",
      "created_at": "Sat, 01 Feb 2020 00:00:00 GMT",
      "has_symptoms": false,
      "number": 3501,
      "status": "in_process",
      "type": "grocery",
      "urgent": false,
      "user": "5fafc2316dc14fbacea2cdd4"
    }
  ]
}
```

2. http://localhost:5000/api/requests?pages=1&page_size=2&phone=79700515&zone=botanica
```
{
  "metadata": {
    "page": 1,
    "page_count": 3,
    "page_size": 2,
    "total_count": 5
  },
  "records": [
    {
      "_id": "5fafc2326dc14fbacea2cde8",
      "beneficiary": "5fafc2326dc14fbacea2cde6",
      "comments": "Cup pressure social affect team get federal modern. Foot audience green ask practice.",
      "created_at": "Wed, 01 Jan 2020 00:00:00 GMT",
      "has_symptoms": false,
      "number": 3505,
      "status": "new",
      "type": "warm_lunch",
      "urgent": false,
      "user": "5fafc2316dc14fbacea2cdd4"
    },
    {
      "_id": "5fafc2326dc14fbacea2cde9",
      "beneficiary": "5fafc2326dc14fbacea2cde6",
      "cluster": "5fafc2326dc14fbacea2cde7",
      "comments": "Your project space. Table dinner board hotel major final particular.",
      "created_at": "Sun, 02 Feb 2020 00:00:00 GMT",
      "has_symptoms": false,
      "number": 3506,
      "status": "in_process",
      "type": "grocery",
      "urgent": false,
      "user": "5fafc2316dc14fbacea2cdd4"
    }
  ]
}
```

3. http://localhost:5000/api/requests?pages=1&page_size=2&created_at=2020-01-04T00%3A00%3A00.000Z
```
{
  "metadata": {
    "page": 1,
    "page_count": 3,
    "page_size": 2,
    "total_count": 5
  },
  "records": [
    {
      "_id": "5fafc2326dc14fbacea2cde8",
      "beneficiary": "5fafc2326dc14fbacea2cde6",
      "comments": "Cup pressure social affect team get federal modern. Foot audience green ask practice.",
      "created_at": "Wed, 01 Jan 2020 00:00:00 GMT",
      "has_symptoms": false,
      "number": 3505,
      "status": "new",
      "type": "warm_lunch",
      "urgent": false,
      "user": "5fafc2316dc14fbacea2cdd4"
    },
    {
      "_id": "5fafc2326dc14fbacea2cde9",
      "beneficiary": "5fafc2326dc14fbacea2cde6",
      "cluster": "5fafc2326dc14fbacea2cde7",
      "comments": "Your project space. Table dinner board hotel major final particular.",
      "created_at": "Sun, 02 Feb 2020 00:00:00 GMT",
      "has_symptoms": false,
      "number": 3506,
      "status": "in_process",
      "type": "grocery",
      "urgent": false,
      "user": "5fafc2316dc14fbacea2cdd4"
    }
  ]
}
```

### CODE REVIEW

**Comment by johnsmithm** [comment]
hi, we need to search by not exact match, also filter by status.

**Comment by johnsmithm** [comment]
if you could integrate also it into /api/requests/1/5 will be better. We need info about the beneficiary and cluster/volunteer in the records.

**Comment by serghei-rubailo** [comment]
Hi,
Ok, I've integrated not exact search by first name/last name/phone to /api/requests/1/5.
Please use 'query' parameter to search by first name/last name/phone

Have added exact search by zone and created_at.
Search by request status was added before.

Add changes to swagger

Unnecessary changes were reverted.

1. http://localhost:5000/api/requests/filters/1/30?query=Jora%20B&status=canceled
```
{
  "count": 1, 
  "list": [
    {
      "_id": "5fafc2326dc14fbacea2cde4", 
      "beneficiary": {
        "_id": "5fafc2326dc14fbacea2cddf", 
        "first_name": "Jora", 
        "last_name": "Bricic\u0103", 
        "latitude": 47.03421007926646, 
        "longitude": 28.845019996559724, 
        "zone": "botanica"
      }, 
      "comments": "Agree meeting himself me write need. Defense national smile itself she. Floor act morning thought make letter.", 
      "created_at": "Wed, 01 Apr 2020 00:00:00 GMT", 
      "has_symptoms": false, 
      "number": 3503, 
      "status": "canceled", 
      "type": "medicine", 
      "urgent": false, 
      "volunteer": {
        "_id": "5fafc2326dc14fbacea2cdd7", 
        "cluster_id": "5fafc2326dc14fbacea2cde0", 
        "first_name": "Serghei", 
        "last_name": "Volkov"
      }
    }
  ]
}
```

2. http://localhost:5000/api/requests/filters/1/1?zone=botanica
```
{
  "count": 10, 
  "list": [
    {
      "_id": "5fafc2326dc14fbacea2cdec", 
      "beneficiary": {
        "_id": "5fafc2326dc14fbacea2cde6", 
        "first_name": "Nicolae", 
        "last_name": "Popa", 
        "latitude": 47.03426007926646, 
        "longitude": 28.845011996559723, 
        "zone": "botanica"
      }, 
      "comments": "Consider either include whom. Large effort sea western ready. Director want particularly.", 
      "created_at": "Sat, 02 May 2020 00:00:00 GMT", 
      "has_symptoms": false, 
      "number": 3509, 
      "status": "archived", 
      "type": "medicine", 
      "urgent": false, 
      "volunteer": {
        "_id": "5fafc2326dc14fbacea2cdd8", 
        "cluster_id": "5fafc2326dc14fbacea2cde7", 
        "first_name": "Valerii", 
        "last_name": "Rever"
      }
    }
  ]
}
```

3. http://localhost:5000/api/requests/filters/1/1?created_at=2020-01-04T00:00:00.000Z
```
{
  "count": 5, 
  "list": [
    {
      "_id": "5fafc2326dc14fbacea2cdec", 
      "beneficiary": {
        "_id": "5fafc2326dc14fbacea2cde6", 
        "first_name": "Nicolae", 
        "last_name": "Popa", 
        "latitude": 47.03426007926646, 
        "longitude": 28.845011996559723, 
        "zone": "botanica"
      }, 
      "comments": "Consider either include whom. Large effort sea western ready. Director want particularly.", 
      "created_at": "Sat, 02 May 2020 00:00:00 GMT", 
      "has_symptoms": false, 
      "number": 3509, 
      "status": "archived", 
      "type": "medicine", 
      "urgent": false, 
      "volunteer": {
        "_id": "5fafc2326dc14fbacea2cdd8", 
        "cluster_id": "5fafc2326dc14fbacea2cde7", 
        "first_name": "Valerii", 
        "last_name": "Rever"
      }
    }
  ]
}
```

**Comment by johnsmithm** [comment]
looks good, thanks @serghei-rubailo for help

**Pull request merged**
