### PR TITLE
Create Request model

### LINKED ISSUE #91: VB-8: Create Request model
1. Add enums associated with the request model:
```
    RequestsStatus:
        - new
        - confirmed
        - in_process
        - canceled
        - solved
        - archived
```
2. Create Request model as described below:
```
    Request:
       beneficiary:
          type: Beneficiary
       user:
          type: User
       status:
          type: RequestStatus
       secret:
          type: string
       urgent:
          type: boolean
       comments:
          type: string
       has_symptoms:
          type: boolean
       cluster:
          type: Cluster
       created_at:
          type: date-time
      required:
        - beneficiary
        - user
        - status
```

### PR DESCRIPTION
**Pull request by RomanCudreavtev**
Closed #91 #92 #93 #90 #89 #88 #84

### CODE REVIEW

**Review by johnsmithm — CHANGES_REQUESTED** [review]
just the volunteer model need to be in the file volunteer_model.py, for all the other entities need be created separated files like notification_model.py benificiary_model.py users_model.py

**Comment by johnsmithm** [comment]
also before working on a issue, it is recommended to write a comment that you will be working on it, so that no two persons will work on the same issue at the same time. Link all the issues I the sidebar.

**Comment by johnsmithm** [comment]
@RomanCudreavtev any updates?

**Comment by RomanCudreavtev** [comment]
> @RomanCudreavtev any updates?

Hello, i had already uploaded  fixes related your last comment. Please check

**Comment by johnsmithm** [comment]
@RomanCudreavtev last commit is from 10 days ago. and there is just one file. could you make a file for each model entity?

**Comment by RomanCudreavtev** [comment]
I had already committed 7 files 
**RomanCudreavtev wants to merge 7 commits into code4moldova:development from RomanCudreavtev:development**

**Comment by johnsmithm** [comment]
this are seven commit, look at the number of changed files. it is just one file volunteer_model.py

**Comment by RomanCudreavtev** [comment]
HM, i see, I will recheck to day after work, but i had committe direct from IDE, and now i have new 7 files (entities)

**Comment by johnsmithm** [comment]
@RomanCudreavtev  this error appears when i have run `docker-compose up` and when to  `localhost:5000`
```
flask.cli.NoAppException: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/app/backend/app.py", line 9, in <module>
    from endpoints import (
  File "/app/backend/endpoints/__init__.py", line 1, in <module>
    from .beneficiary import get_beneficiaries_by_filters, getBeneficiary, registerBeneficiary, updateBeneficiary
  File "/app/backend/endpoints/beneficiary.py", line 9, in <module>
    from endpoints import volunteer
  File "/app/backend/endpoints/volunteer.py", line 11, in <module>
    from models import Beneficiary, Operator, Volunteer
  File "/app/backend/models/__init__.py", line 1, in <module>
    from .volunteer_model import Volunteer, Beneficiary_request, Beneficiary, Operator, Tags
  File "/app/backend/models/volunteer_model.py", line 24, in <module>
    from backend.models.beneficiary_model import Beneficiary
ModuleNotFoundError: No module named 'backend'
```

**Comment by RomanCudreavtev** [comment]
> @RomanCudreavtev this error appears when i have run `docker-compose up` and when to `localhost:5000`
> 
> ```
> flask.cli.NoAppException: While importing "app", an ImportError was raised:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
>     __import__(module_name)
>   File "/app/backend/app.py", line 9, in <module>
>     from endpoints import (
>   File "/app/backend/endpoints/__init__.py", line 1, in <module>
>     from .beneficiary import get_beneficiaries_by_filters, getBeneficiary, registerBeneficiary, updateBeneficiary
>   File "/app/backend/endpoints/beneficiary.py", line 9, in <module>
>     from endpoints import volunteer
>   File "/app/backend/endpoints/volunteer.py", line 11, in <module>
>     from models import Beneficiary, Operator, Volunteer
>   File "/app/backend/models/__init__.py", line 1, in <module>
>     from .volunteer_model import Volunteer, Beneficiary_request, Beneficiary, Operator, Tags
>   File "/app/backend/models/volunteer_model.py", line 24, in <module>
>     from backend.models.beneficiary_model import Beneficiary
> ModuleNotFoundError: No module named 'backend'
> ```

Fixed

**Review by johnsmithm — APPROVED** [review]

**Pull request merged**
