### PR TITLE
Vb20 filter the beneficiary using phone and landline

### LINKED ISSUE #116: VB20 - filter the beneficiary using phone and landline
when a new request is added the system should be able to identify if the beneficiary already exists in the system.

### PR DESCRIPTION
**Pull request by serghei-rubailo**
### What does it fix?

Closes #116 

1. Have added "phone" and "landline" parameters to search for beneficiary by exact value 
To search by "phone" and "landline" we have to add "phone" and "landline" parameters in GET HTTP parameters
Example: http://localhost:5000/api/beneficiary/filters/1/5?landline=22835600&phone=68078000
It will returns result only on exact match.

2. Have added "landline" value for test beneficiaries in seeds.py

3. Have optimized logic of get_beneficiaries_by_filters to be more readable and to more easy add new parameters to exact search.

### How has it been tested?

1. http://localhost:5000/api/beneficiary/filters/1/5?landline=22835600&phone=68078000 - returns one beneficiary with exact phone and landline
```
{
  "count": 1, 
  "list": [
    {
      "_id": "5f8d4ee2ba0f4caff7c5ea25", 
      "landline": "22835600", 
      "last_name": "Troscot", 
      "offer": "1", 
      "phone": "68078000", 
       .......
    }
  ]
}
```

2. http://localhost:5000/api/beneficiary/filters/1/5?landline=22022022 
```
{
  "count": 1, 
  "list": [
    {
      "_id": "5f8d4ee2ba0f4caff7c5ea13", 
      "first_name": "Valerii", 
      "landline": "22022022", 
        .....
    }
  ]
}
```

3. http://localhost:5000/api/beneficiary/filters/1/5?phone=79000003
```
{
  "count": 1, 
  "list": [
    {
      "_id": "5f8d4ee2ba0f4caff7c5ea13", 
      "first_name": "Valerii", 
      "last_name": "Krisp", 
      "phone": "79000003", 
      .....
    }
  ]
}
```

4. http://localhost:5000/api/beneficiary/filters/1/5?query=Ghenadii%20Sidorov
```
[{
  "count": 1, 
  "list": [
    {
      "_id": "5f8d4ee2ba0f4caff7c5ea14", 
      "first_name": "Ghenadii", 
      "last_name": "Sidorov", 
       ......
    }
  ]
}]
```

### CODE REVIEW

**Comment by johnsmithm** [comment]
image

**Comment by johnsmithm** [comment]
@serghei-rubailo can you fix the swagger?

**Comment by serghei-rubailo** [comment]
Hi!
Sorry, didn't check if swagger run.
Yes, will do it as soon as will be near my PC

**Comment by serghei-rubailo** [comment]
Swagger was fixed

**Comment by johnsmithm** [comment]
could you merge the development into this PR first?

**Pull request closed without merging**
